Add aggregate_list utility function, along with unit tests
MiCurry/SMIOL pull request #72
Opened 2021-09-17 21:58 UTC by mgduda

This PR adds a new utility function, `aggregate_list`, that may be used to
gather arbitrarily sized lists of `SMIOL_Offset` values from all ranks in
a communicator onto a chosen root task in the communicator.

2021-09-20 17:37 UTC, MiCurry requested changes

2021-09-20 17:37 UTC, MiCurry commented on src/smiol_utils.c
> +	}
This `MPI_Gather`, and the `MPI_Reduce` on lines 436-437 seem to be doing relatively the same task, should we reduce them into one? e.g.:

``` C
...

// Allocate counts and displs using comm_size
if (comm_rank == root) {
	*counts = (int *)malloc(sizeof(int) * (size_t)(comm_size));
	*displs = (int *)malloc(sizeof(int) * (size_t)(comm_size));
}

// Gather input counts
err = MPI_Gather((const void *)&n_in32, 1, MPI_INT,
	                      (void *)(*counts), 1, MPI_INT, root, comm);

// Determine n_out
if (comm_rank == root) {
    n_out = 0;
    for (i = 0 ; i < comm_size ; i++) {
        n_out += counts[i];
    } 
}

// Allocate out_list using n_out
if (comm_rank == root) {
	*out_list = (SMIOL_Offset *)malloc(sizeof(SMIOL_Offset)
		                                  * (*n_out))
}

...
```

2021-09-20 17:37 UTC, MiCurry commented on src/smiol_utils.c
> +	}
We could also combine the loop on 467 with the one I proposed above.

2021-09-20 19:46 UTC, mgduda commented on src/smiol_utils.c
> +	int n_out32;
The name was simply to differentiate these variables, though the 32 was definitely a suggestion that these are probably 32-bit values (though the code in no way depends on this). I'll rename `n_in32` to `n_in_i`.

2021-09-20 19:47 UTC, mgduda commented on src/smiol_utils.c
> +	}
Those are good suggestions. I'll push changes to remove the `MPI_Reduce` and to combine loops for computing `displs` and `n_out`.

2021-09-20 19:55 UTC, mgduda commented
@MiCurry I've just pushed an update to this branch with changes based on your suggestions.

2021-09-22 21:41 UTC, MiCurry commented on smiol_runner.c
> +	n_out = -1;
The PGI throws the following warning on this line (and the ones below): 

``` c
"smiol_runner.c", line 3848: warning: integer conversion resulted in a change
          of sign
        n_out = -1;
```

Setting an unsigned integer to -1 seems pretty common and not necessarily against C standard, from what I can tell. GNU and Intel seem to be okay with it. Regardless, we can get rid of these warnings by using the `SIZE_MAX` macro from `stdint.h`:

```c
n_out = SIZE_MAX;
```

2021-09-22 21:42 UTC, MiCurry commented on smiol_runner.c
> +	n_out = -1;
``` c
n_out = SIZE_MAX;
```

2021-09-22 21:42 UTC, MiCurry commented on smiol_runner.c
> +		n_out = -1;
PGI warning appears here as well..

2021-09-22 21:42 UTC, MiCurry commented on smiol_runner.c
> +		n_out = -1;
PGI warning appears here as well..

2021-09-22 21:42 UTC, MiCurry commented on smiol_runner.c
> +		n_out = -1;
PGI warning appears here as well..

2021-09-22 21:49 UTC, MiCurry commented
Other than the PGI warnings this branch looks good to go 👍

2021-09-23 00:32 UTC, mgduda commented on smiol_runner.c
> +		n_out = -1;
Fixed.

2021-09-23 00:32 UTC, mgduda commented on smiol_runner.c
> +		n_out = -1;
Fixed.

2021-09-23 00:32 UTC, mgduda commented on smiol_runner.c
> +		n_out = -1;
Fixed.

2021-09-23 00:32 UTC, mgduda commented on smiol_runner.c
> +	n_out = -1;
Fixed.

2021-09-23 00:32 UTC, mgduda commented on smiol_runner.c
> +	n_out = -1;
Fixed.

2021-09-23 00:34 UTC, mgduda commented
@MiCurry I've just pushed an additional commit (which I'll squash before merging this PR, though for now it seemed easier to see what I've changed in a separate commit) that addresses the PGI warnings.

Additionally, I've addressed these two warnings in `smiol_utils.c` that were generated by the clang compiler:
```
smiol_utils.c:452:12: warning: implicit conversion changes signedness: 'int' to 'size_t' (aka 'unsigned long') [-Wsign-conversion]
                *n_out = (*counts)[0];
                       ~ ^~~~~~~~~~~~
smiol_utils.c:455:14: warning: implicit conversion changes signedness: 'int' to 'unsigned long' [-Wsign-conversion]
                        *n_out += (*counts)[i];
                               ~~ ^~~~~~~~~~~~
```
In the `smiol_runner.c` test code, I also addressed a substantial number of warnings from clang.

2021-09-23 21:13 UTC, MiCurry approved these changes

2021-09-24 02:13 UTC, merged