Add file format argument to SMIOL_open_file
MiCurry/SMIOL pull request #77
Opened 2023-10-17 21:17 UTC by gdicker1

This PR enhances SMIOL by adding the ability to create files of different formats.

For now there are only two defined corresponding to the CDF2 (NC_64BIT_OFFSET) and CDF5 (NC_64BIT_DATA) formats. This list can be expanded in the future.

As an example use case: if MPAS-A is restarted with a NC_64BIT_OFFSET restart file, that should be detected and output files created should be the same or compatible format. Before this change, SMIOL would not be able to use create files in any format besides NC_64BIT_DATA.

2023-11-15 21:09 UTC, mgduda commented on src/smiol_codes.inc
> +#define SMIOL_CDF5_FRMT        (3001)
I would propose that these new constants begin with `SMIOL_FORMAT_` and end with the names of supported formats; i.e., `SMIOL_FORMAT_CDF2` and `SMIOL_FORMAT_CDF5`.

2023-11-15 21:25 UTC, mgduda commented on src/smiol.c
> +	if ((frmt ^ SMIOL_CDF2_FRMT) == 0)
With the conditionals structured as they are, the use of a bitwise xor seems like it doesn't gain us much over a simple comparison, and in my opinion the use of `^` is less readable. I'd propose either a `switch` statement or `if` statements with simple `==` comparisons.

2023-11-15 21:34 UTC, mgduda commented on src/smiol.c
> +	int filecmode; // file format from library
Towards the goal of keeping the scope of variables as narrow as possible, we could move this declaration after line 298 (in the modified code; line 292 in the original code).

2023-11-15 21:37 UTC, mgduda commented on src/smiol.c
> +			}
With the tests here for supported file formats, is there any value in calling the `check_file_format` function?

2023-11-15 21:38 UTC, mgduda requested changes
I haven't yet looked through the tests. As a first pass, I thought I'd just offer some comments on the SMIOL library code changes.

2023-11-20 19:33 UTC, gdicker1 commented on src/smiol.c
> +			}
I don't think so. Maybe I should just remove the `check_file_format`?

I also see I need to update this return statement to deal with `file` correctly

2023-11-20 19:38 UTC, gdicker1 commented on src/smiolf.F90
> +    !>  set the file format. Otherwise fformat is ignored.
What do you think of:

```
     !>  When a file is opened with SMIOL_FILE_CREATE, the fformat optional argument
     !>  is used to set the file format. Otherwise, fformat is ignored. If not 
     !>  present, the default file format is SMIOL_CDF5_FRMT.
```

2023-11-20 20:34 UTC, mgduda commented on src/smiol.c
> +			}
In this case, I think less code would be better, so I'd be fine with removing the `check_file_format` function.

2023-11-20 20:38 UTC, mgduda commented on src/smiolf.F90
> +    !>  set the file format. Otherwise fformat is ignored.
I think that sounds fine. I'd only suggest that in this text (and also around line 205), we could say "When a file is opened with a mode of SMIOL_FILE_CREATE", otherwise it's slightly ambiguous what it means to open a file with `SMIOL_FILE_CREATE`.

2023-11-20 20:55 UTC, gdicker1 commented on src/smiolf.F90
> +    !>  set the file format. Otherwise fformat is ignored.
Understood. I'll update this in smiolf.F90 and in smiol.c

2023-11-20 21:04 UTC, gdicker1 commented
These force pushes should have resolved the comments you made @mgduda. Please let me know if I missed anything!

2023-12-26 22:14 UTC, mgduda requested changes
I think we're almost there. Just a few more small changes.

2023-12-26 22:14 UTC, mgduda commented on src/smiol.c
> +		return "argument is an invalid create mode for library";
I don't have any suggestion to offer at the moment, but there's a bit of a difference in terminology: the argument to `SMIOL_open_file` suggests a "format", while this message refers to a "create mode". Perhaps sticking with the idea of a format here, and describing the error as something like "invalid format for file creation"?

2023-12-26 22:14 UTC, mgduda commented on src/smiol.c
> +		int filecmode; // file format from library
This could actually be declared within the scope of the if-block beginning at line 296.

2023-12-26 22:14 UTC, mgduda commented on src/smiol.c
> +			}
This could be made to be more compact (and more in line with the style of conditional blocks elsewhere) by writing it as follows:
```c
                        /*
                         * Convert fformat to a PNetCDF file creation mode
                         */
                        if (fformat == SMIOL_FORMAT_CDF2) {
                                filecmode = NC_64BIT_OFFSET;
                        } else if (fformat == SMIOL_FORMAT_CDF5) {
                                filecmode = NC_64BIT_DATA;
                        } else {
                                free((*file));
                                (*file) = NULL;
                                MPI_Comm_free(&io_file_comm);
                                MPI_Comm_free(&io_group_comm);
                                return SMIOL_FORMAT_INVALID;
                        }

```
(I didn't actually test the additional code to free communicators, but I think those should be present.)

2023-12-26 22:14 UTC, mgduda commented on smiol_runner.F90
> +        ierr = SMIOLf_open_file(context, 'smiolf_invalid_frmt.nc', &
Perhaps we could choose a different filename here -- something like `smiolf_cdf2.nc`?

2023-12-26 22:14 UTC, mgduda commented on smiol_runner.F90
> +        end if
Just to avoid un-freed memory (from open files in the PNetCDF library), I think it would be worth closing the file that was presumed to have been successfully created at this point.

2023-12-26 22:14 UTC, mgduda commented on smiol_runner.F90
> +
Should we add another test to verify that the `fformat` argument is ignored if we open a file for reading?

2024-01-02 18:31 UTC, gdicker1 commented on src/smiol.c
> +		return "argument is an invalid create mode for library";
Yeah, this shows where I was uncertain on terms. I think the text you suggested is great for how this error code is being used (can be edited later if the use is modified/expanded).

2024-01-03 01:05 UTC, gdicker1 commented on smiol_runner.F90
> +
This should be handled after the most recent force pushes (158625f to 8242b63 and 8242b63 to 11251a7). At least, I check for SMIOL_FILE_READ. Should I include another for an invalid fformat for SMIOL_FILE_WRITE?

2024-01-03 01:06 UTC, gdicker1 commented
@mgduda This should be ready for re-review. I did 2 force-pushes because I forgot to include tests for SMIOL_INVALID_FORMAT in the error string testing in the first push.

2024-01-04 22:42 UTC, mgduda commented
With the changes in this PR, it looks like we're now getting failures in some of the unit tests:
```
********************************************************************************
************ SMIOL_define_dim / SMIOL_inquire_dim ******************************

Handle NULL file handle (SMIOL_define_dim): PASS
Handle NULL dimension name (SMIOL_define_dim): PASS
Everything OK - unlimited dimension (SMIOL_define_dim): PASS
Everything OK - small non-record dimension (SMIOL_define_dim): PASS
Everything OK - large non-record dimension (SMIOL_define_dim): FAIL - SMIOL_SUCCESS was not returned
Handle NULL file handle (SMIOL_inquire_dim): PASS
Handle NULL dimension name (SMIOL_inquire_dim): PASS
Handle NULL dimension size and NULL unlimited argument (SMIOL_inquire_dim): PASS
Handle undefined dimension (SMIOL_inquire_dim): PASS (NetCDF: Invalid dimension ID or name)
Everything OK - unlimited dimension (SMIOL_inquire_dim): PASS
Everything OK - small non-record dimension (SMIOL_inquire_dim): PASS
Everything OK - large non-record dimension (SMIOL_inquire_dim): FAIL - SMIOL_SUCCESS was not returned
Everything OK - checking if Time is the unlimited dimension (SMIOL_inquire_dim): PASS
Everything OK - checking if nCells is not the unlimited dimension (SMIOL_inquire_dim): PASS
Existing file - unlimited dimension (SMIOL_inquire_dim): PASS
Existing file - small non-record dimension (SMIOL_inquire_dim): PASS
Existing file - large non-record dimension (SMIOL_inquire_dim): FAIL - SMIOL_SUCCESS was not returned

3 tests FAILED!
```

2024-01-04 22:48 UTC, mgduda commented on smiol_runner.F90
> +
I suppose it would be best to verify that file formats are ingored (by passing one that is invalid) for both files opened for reading and existing files opened for writing. Just duplicating the test for `SMIOL_FILE_READ` and differentiating the two tests in their comments and log messages should be sufficient.

2024-01-04 22:49 UTC, mgduda commented on smiol_runner.F90
> +               ierrcount = ierrcount +1
It's minor, but here and a few other places, I'd suggest adding a space in `+1`.

2024-01-04 22:50 UTC, mgduda commented on smiol_runner.F90
> +               write(test_log,'(a)') 'FAIL - unable to close file opened with an ignored invalid file format'
I think there's missing code above to attempt to close the file.

2024-01-06 04:54 UTC, gdicker1 commented
> With the changes in this PR, it looks like we're now getting failures in some of the unit tests:

Looks like this was because I was using logic like the below. These failures implied that `NC_64_BIT_OFFSET` was being used instead of `NC_64BIT_DATA`. I should have used `==` instead of `&`

```
if (fformat & SMIOL_FORMAT_CDF2) {
        filecmode = NC_64BIT_OFFSET;
}        filecmode = NC_64BIT_DATA;
} else {
        // Omitted
}
```

Should be ready for re-review!

2024-01-16 21:45 UTC, mgduda requested changes
Just a one-line change, and I think we'll be all set!

2024-01-16 21:45 UTC, mgduda commented on smiol_runner.c
> +			fprintf(test_log, "FAIL - unable to close newly created CDF2 format file\n");
I think we need to increment `errcount` here.

2024-01-22 23:20 UTC, mgduda approved these changes
Nice work -- this looks good!

2024-01-22 23:27 UTC, merged